services:
  jekyll:
    image: quay.io/keboola/docs-jekyll
    tty: true
    stdin_open: true
    volumes:
      - ./:/code:cached
    working_dir: /code
    ports:
      - "4000:4000"
    command: jekyll serve --watch -H 0.0.0.0 --force_polling

  aws:
    image: public.ecr.aws/aws-cli/aws-cli:latest
    volumes:
      - ./:/code
    working_dir: /code
