#!/usr/bin/env node
/**
 * convert-nav.mjs
 *
 * Reads _data/navigation.yml (the Jekyll sidebar) and generates
 * src/sidebar.mjs — a Starlight-compatible sidebar config.
 *
 * Usage:  node scripts/convert-nav.mjs
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

// ---------------------------------------------------------------------------
// 1. Read & parse the navigation YAML
// ---------------------------------------------------------------------------
const navPath = resolve(ROOT, '_data', 'navigation.yml');
const navYaml = readFileSync(navPath, 'utf-8');
const navData = yaml.load(navYaml);

// ---------------------------------------------------------------------------
// 2. Helper: strip leading/trailing slashes to produce a Starlight slug
// ---------------------------------------------------------------------------
function toSlug(url) {
  if (!url) return '';
  return url.replace(/^\/+/, '').replace(/\/+$/, '');
}

// ---------------------------------------------------------------------------
// 3. Recursive converter
// ---------------------------------------------------------------------------
function convertItem(item) {
  const slug = toSlug(item.url);
  const hasChildren = Array.isArray(item.items) && item.items.length > 0;

  // Special case: Home page
  if (item.url === '/') {
    return { label: 'Home', slug: 'index' };
  }

  // Leaf node — no children
  if (!hasChildren) {
    return { slug };
  }

  // Branch node — has children
  // The parent page itself goes first, then each child is converted recursively
  const childItems = item.items.map(convertItem);
  return {
    label: item.title,
    collapsed: true,
    items: [
      { label: 'Overview', slug },  // parent page labeled "Overview" to avoid duplicating group name
      ...childItems,
    ],
  };
}

// ---------------------------------------------------------------------------
// 4. Convert the entire tree
// ---------------------------------------------------------------------------
const sidebar = navData.items.map(convertItem);

// ---------------------------------------------------------------------------
// 5. Serialize to JavaScript source
// ---------------------------------------------------------------------------
function serializeValue(value, indent = 0) {
  const pad = '  '.repeat(indent);
  const innerPad = '  '.repeat(indent + 1);

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const entries = value.map((v) => `${innerPad}${serializeValue(v, indent + 1)},`);
    return `[\n${entries.join('\n')}\n${pad}]`;
  }

  if (typeof value === 'object' && value !== null) {
    const keys = Object.keys(value);

    // Compact small objects on one line: { slug: 'foo' } or { label: 'x', slug: 'y' }
    if (keys.length <= 2 && keys.every((k) => typeof value[k] === 'string')) {
      const parts = keys.map((k) => `${k}: ${JSON.stringify(value[k])}`);
      return `{ ${parts.join(', ')} }`;
    }

    const entries = keys.map((k) => {
      const v = value[k];
      return `${innerPad}${k}: ${serializeValue(v, indent + 1)},`;
    });
    return `{\n${entries.join('\n')}\n${pad}}`;
  }

  return JSON.stringify(value);
}

const sidebarSource = `// Auto-generated by scripts/convert-nav.mjs — do not edit by hand.
// Re-generate with:  node scripts/convert-nav.mjs

export const sidebar = ${serializeValue(sidebar, 0)};
`;

// ---------------------------------------------------------------------------
// 6. Write src/sidebar.mjs
// ---------------------------------------------------------------------------
const outPath = resolve(ROOT, 'src', 'sidebar.mjs');
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, sidebarSource, 'utf-8');

console.log(`Wrote ${sidebar.length} top-level sidebar entries to ${outPath}`);
