name: "Build and deploy"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: "Build and deploy"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - name: "Install dependencies"
        run: npm ci
      - name: "Build"
        run: npm run build
      - name: "Deploy"
        run: |
          aws s3 sync dist s3://help.keboola.com --delete --acl "public-read" --cache-control "max-age=600" --region us-east-1
